### ISSUE TITLE
fix: application form link 404s

### ISSUE THREAD

**Issue by dargmuesli** [safety-in-bytes/safety-in-bytes.github.io#2]
This link 404s: https://safetyinbytes.de/call-for-participation
The form can only be reached by going to https://safetyinbytes.de/ first and clicking the button on that page. Instead, it should be possible to access the form directly using the link given first.
This will be especially important once we hand the form link to our speakers independently from the content of the start page.

**Comment by myyxl** [comment]
Should be fixed. Please check.
